#version: 2
#updates:
#  - package-ecosystem: 'npm'
#    directory: '/'
#    rebase-strategy: 'auto'
#    target-branch: 'develop'
#    schedule:
#      interval: 'weekly'
#    labels:
#      - 'dependencies'
#      - 'automerge'
