version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'automerge'

automerge:
  enabled: true
  strategies:
    - type: 'all'
      pull-request:
        merge-method: 'merge'
