version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    rebase-strategy: 'auto'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'automerge'
    ignore:
      - dependency-name: '*'
        versions: ['*']
        branch: 'main'
