version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'automerge'
    allow:
      - dependency-type: 'all'
    versioning-strategy: increase
    groups:
      all-updates:
        patterns:
          - '*'

automerge:
  enabled: true
  strategies:
    - type: 'all'
      pull-request:
        merge-method: 'merge'
