/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    ArchiveChip: typeof import('./src/components/ArchiveChip.vue')['default']
    ButtonCard: typeof import('./src/components/ButtonCard.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    CookieBanner: typeof import('./src/components/cookies/CookieBanner.vue')['default']
    CookieButton: typeof import('./src/components/cookies/CookieButton.vue')['default']
    CookieConsent: typeof import('./src/components/CookieConsent.vue')['default']
    CookieDialog: typeof import('./src/components/cookies/CookieDialog.vue')['default']
    CopyButton: typeof import('./src/components/CopyButton.vue')['default']
    ImageCarosel: typeof import('./src/components/ImageCarosel.vue')['default']
    InlineCode: typeof import('./src/components/InlineCode.vue')['default']
    InlineTextCopy: typeof import('./src/components/InlineTextCopy.vue')['default']
    LangGraph: typeof import('./src/components/LangGraph.vue')['default']
    LatestReleaseChip: typeof import('./src/components/LatestReleaseChip.vue')['default']
    LicenseChip: typeof import('./src/components/LicenseChip.vue')['default']
    LinkableTitle: typeof import('./src/components/LinkableTitle.vue')['default']
    LinkComponent: typeof import('./src/components/LinkComponent.vue')['default']
    MapComponent: typeof import('./src/components/MapComponent.vue')['default']
    MessagePopup: typeof import('./src/components/MessagePopup.vue')['default']
    PayPalBtn: typeof import('./src/components/PayPalBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsAndChips: typeof import('./src/components/StatsAndChips.vue')['default']
    TableOfContents: typeof import('./src/components/TableOfContents.vue')['default']
  }
}
