/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    ArchiveChip: typeof import('./components/ArchiveChip.vue')['default']
    ArmV1: typeof import('./views/projects/RoboticArm/ArmV1.vue')['default']
    ArmV2: typeof import('./views/projects/RoboticArm/ArmV2.vue')['default']
    ButtonCard: typeof import('./components/ButtonCard.vue')['default']
    CodeBlock: typeof import('./components/CodeBlock.vue')['default']
    ContactView: typeof import('./views/ContactView.vue')['default']
    CookieConsent: typeof import('./components/CookieConsent.vue')['default']
    CopyButton: typeof import('./components/CopyButton.vue')['default']
    DonateView: typeof import('./views/DonateView.vue')['default']
    DropdownMenu: typeof import('./components/DropdownMenu.vue')['default']
    FileOrganizerView: typeof import('./views/archive/FileOrganizerView.vue')['default']
    FileShareView: typeof import('./views/projects/FileShareView.vue')['default']
    HomeView: typeof import('./views/HomeView.vue')['default']
    ImageCarosel: typeof import('./components/ImageCarosel.vue')['default']
    InlineCode: typeof import('./components/InlineCode.vue')['default']
    InlineTextCopy: typeof import('./components/InlineTextCopy.vue')['default']
    LangGraph: typeof import('./components/LangGraph.vue')['default']
    LatestReleaseChip: typeof import('./components/LatestReleaseChip.vue')['default']
    LicenseChip: typeof import('./components/LicenseChip.vue')['default']
    LinkComponent: typeof import('./components/LinkComponent.vue')['default']
    LinkImage: typeof import('./components/LinkImage.vue')['default']
    MapComponent: typeof import('./components/MapComponent.vue')['default']
    MessagePopup: typeof import('./components/MessagePopup.vue')['default']
    MinecraftView: typeof import('./views/servers/MinecraftView.vue')['default']
    NotFound: typeof import('./views/NotFound.vue')['default']
    PayPalBtn: typeof import('./components/PayPalBtn.vue')['default']
    PlexOrganizerView: typeof import('./views/projects/PlexOrganizerView.vue')['default']
    PrivacyPolicy: typeof import('./views/PrivacyPolicy.vue')['default']
    RoboticArmView: typeof import('./views/projects/RoboticArmView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsAndChips: typeof import('./components/StatsAndChips.vue')['default']
    T6DroneView: typeof import('./views/projects/T6DroneView.vue')['default']
    ToS: typeof import('./views/ToS.vue')['default']
  }
}
