name: Auto-merge Dependabot updates

on:
  pull_request:
    types:
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js (if you're using npm, adjust if you're using a different package manager)
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: GitHub Action for GitHub API
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: auto-merge

      - name: Auto-merge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
