name: Auto-merge Dependabot updates

on:
  pull_request:
    types:
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Check if PR is mergeable and retry if necessary
        id: check_mergeable
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          RETRY_DELAY=30

          while true; do
            PR_MERGEABLE=$(gh pr view $PR_NUMBER --json mergeable --jq .mergeable)
            PR_MERGE_STATUS=$(gh pr view $PR_NUMBER --json mergeStateStatus --jq .mergeStateStatus)
            if [ "$PR_MERGE_STATUS" == "UNSTABLE" && "$PR_MERGEABLE" == "MERGEABLE"]; then
              echo "PR is mergeable"
              echo "mergeable=true" >> $GITHUB_ENV
              exit 0
            fi
            echo "PR not mergeable. Waiting for $RETRY_DELAY seconds before retrying... ("$PR_MERGEABLE" "$PR_MERGE_STATUS")"
            sleep $RETRY_DELAY
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge
        if: env.mergeable == 'true'
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
