name: Auto Merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:   
  automerge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
      - name: Enable auto-merge (Squash and Merge)
        run: |
          PR_URL=${{ github.event.pull_request.html_url }}
          COMMIT_COUNT=$(gh pr view "$PR_URL" --json commits --jq '.commits | length')
          
          if [ "$COMMIT_COUNT" -gt 1 ]; then
            gh pr merge "$PR_URL" --squash --auto --repo ${{ github.repository }}
          else
            gh pr merge "$PR_URL" --auto --repo ${{ github.repository }}
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
