name: Docker image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run the workflow on'
        required: true
        type: choice
        options:
          - main
          - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "DATE_LABEL=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/toomas633/toomas633:latest
          labels: |
            org.opencontainers.image.created=${{ env.DATE_LABEL }}
            org.opencontainers.image.version=latest
          platforms: linux/amd64,linux/arm64,linux/arm32
          cache-from: type=registry,ref=ghcr.io/toomas633/toomas633:buildcache
          cache-to: type=registry,ref=ghcr.io/toomas633/toomas633:buildcache,mode=max
