name: Docker Test Build
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: meta
        run: echo "date_label=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Read version from package.json
        id: pkg
        run: echo "package_version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: |
            ghcr.io/toomas633/toomas633:dev
            ghcr.io/toomas633/toomas633:${{ steps.pkg.outputs.package_version }}
          labels: |
            org.opencontainers.image.created=${{ steps.meta.outputs.date_label }}
            org.opencontainers.image.version=${{ steps.pkg.outputs.package_version }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/toomas633/toomas633:buildcache
          cache-to: type=registry,ref=ghcr.io/toomas633/toomas633:buildcache,mode=max
